export const states = [
  "Abia",
  "Adamawa",
  "Akwa Ibom",
  "Anambra",
  "Bauchi",
  "Bayelsa",
  "Benue",
  "Borno",
  "Cross River",
  "Delta",
  "Ebonyi",
  "Edo",
  "Ekiti",
  "Enugu",
  "FCT - Abuja",
  "Gombe",
  "Imo",
  "Jigawa",
  "Kaduna",
  "Kano",
  "Katsina",
  "Kebbi",
  "Kogi",
  "Kwara",
  "Lagos",
  "Nasarawa",
  "Niger",
  "Ogun",
  "Ondo",
  "Osun",
  "Oyo",
  "Plateau",
  "Rivers",
  "Sokoto",
  "Taraba",
  "Yobe",
  "Zamfara",
];

export const countries = [
  "Afghanistan",
  "Albania",
  "Algeria",
  "Andorra",
  "Angola",
  "Antigua and Barbuda",
  "Argentina",
  "Armenia",
  "Australia",
  "Austria",
  "Azerbaijan",
  "Bahamas",
  "Bahrain",
  "Bangladesh",
  "Barbados",
  "Belarus",
  "Belgium",
  "Belize",
  "Benin",
  "Bhutan",
  "Bolivia",
  "Bosnia and Herzegovina",
  "Botswana",
  "Brazil",
  "Brunei",
  "Bulgaria",
  "Burkina Faso",
  "Burundi",
  "Cabo Verde",
  "Cambodia",
  "Cameroon",
  "Canada",
  "Central African Republic",
  "Chad",
  "Chile",
  "China",
  "Colombia",
  "Comoros",
  "Congo, Republic of the",
  "Congo, Democratic Republic of the",
  "Costa Rica",
  "Croatia",
  "Cuba",
  "Cyprus",
  "Czech Republic",
  "Denmark",
  "Djibouti",
  "Dominica",
  "Dominican Republic",
  "Ecuador",
  "Egypt",
  "El Salvador",
  "Equatorial Guinea",
  "Eritrea",
  "Estonia",
  "Eswatini",
  "Ethiopia",
  "Fiji",
  "Finland",
  "France",
  "Gabon",
  "Gambia",
  "Georgia",
  "Germany",
  "Ghana",
  "Greece",
  "Grenada",
  "Guatemala",
  "Guinea",
  "Guinea-Bissau",
  "Guyana",
  "Haiti",
  "Honduras",
  "Hungary",
  "Iceland",
  "India",
  "Indonesia",
  "Iran",
  "Iraq",
  "Ireland",
  "Israel",
  "Italy",
  "Jamaica",
  "Japan",
  "Jordan",
  "Kazakhstan",
  "Kenya",
  "Kiribati",
  "Korea, North",
  "Korea, South",
  "Kosovo",
  "Kuwait",
  "Kyrgyzstan",
  "Laos",
  "Latvia",
  "Lebanon",
  "Lesotho",
  "Liberia",
  "Libya",
  "Liechtenstein",
  "Lithuania",
  "Luxembourg",
  "Madagascar",
  "Malawi",
  "Malaysia",
  "Maldives",
  "Mali",
  "Malta",
  "Marshall Islands",
  "Mauritania",
  "Mauritius",
  "Mexico",
  "Micronesia",
  "Moldova",
  "Monaco",
  "Mongolia",
  "Montenegro",
  "Morocco",
  "Mozambique",
  "Myanmar",
  "Namibia",
  "Nauru",
  "Nepal",
  "Netherlands",
  "New Zealand",
  "Nicaragua",
  "Niger",
  "Nigeria",
  "North Macedonia",
  "Norway",
  "Oman",
  "Pakistan",
  "Palau",
  "Palestine",
  "Panama",
  "Papua New Guinea",
  "Paraguay",
  "Peru",
  "Philippines",
  "Poland",
  "Portugal",
  "Qatar",
  "Romania",
  "Russia",
  "Rwanda",
  "Saint Kitts and Nevis",
  "Saint Lucia",
  "Saint Vincent and the Grenadines",
  "Samoa",
  "San Marino",
  "Sao Tome and Principe",
  "Saudi Arabia",
  "Senegal",
  "Serbia",
  "Seychelles",
  "Sierra Leone",
  "Singapore",
  "Slovakia",
  "Slovenia",
  "Solomon Islands",
  "Somalia",
  "South Africa",
  "South Sudan",
  "Spain",
  "Sri Lanka",
  "Sudan",
  "Suriname",
  "Sweden",
  "Switzerland",
  "Syria",
  "Taiwan",
  "Tajikistan",
  "Tanzania",
  "Thailand",
  "Timor-Leste",
  "Turkey",
  "Turkmenistan",
  "Tuvalu",
  "Uganda",
  "Ukraine",
  "United Arab Emirates",
  "United Kingdom",
  "United States",
  "Uruguay",
  "Uzbekistan",
  "Vanuatu",
  "Vatican City",
  "Venezuela",
  "Vietnam",
  "Yemen",
  "Zambia",
  "Zimbabwe",
];

export const localAirports = [
  { id: "ABV", name: "Nnamdi Azikiwe International Airport, Abuja" },
  { id: "LOS", name: "Murtala Muhammed International Airport, Lagos" },
  { id: "PHC", name: "Port Harcourt International Airport, Port Harcourt" },
  { id: "KAN", name: "Mallam Aminu Kano International Airport, Kano" },
  { id: "ABA", name: "Aba Airport, Aba" },
  { id: "ENU", name: "Enugu Airport, Enugu" },
  { id: "JOS", name: "Jos Airport, Jos" },
  { id: "ILR", name: "Ilorin Airport, Ilorin" },
  { id: "MDG", name: "Maiduguri Airport, Maiduguri" },
  { id: "OSU", name: "Osubi Airport, Warri" },
  { id: "SUK", name: "Sukur Airport, Sukur" },
  { id: "ZAR", name: "Zaria Airport, Zaria" },
];

export const internationalAirports = [
  // North America
  { id: "JFK", name: "John F. Kennedy International Airport, New York, USA" },
  { id: "LAX", name: "Los Angeles International Airport, Los Angeles, USA" },
  { id: "ORD", name: "O'Hare International Airport, Chicago, USA" },
  { id: "YYZ", name: "Toronto Pearson International Airport, Toronto, Canada" },
  { id: "YVR", name: "Vancouver International Airport, Vancouver, Canada" },

  // Europe
  { id: "LHR", name: "Heathrow Airport, London, UK" },
  { id: "CDG", name: "Charles de Gaulle Airport, Paris, France" },
  { id: "FRA", name: "Frankfurt Airport, Frankfurt, Germany" },
  { id: "AMS", name: "Amsterdam Airport Schiphol, Amsterdam, Netherlands" },
  { id: "MAD", name: "Adolfo Suárez Madrid-Barajas Airport, Madrid, Spain" },
  { id: "ZRH", name: "Zurich Airport, Zurich, Switzerland" },

  // Asia
  { id: "DXB", name: "Dubai International Airport, Dubai, UAE" },
  { id: "HKG", name: "Hong Kong International Airport, Hong Kong" },
  { id: "ICN", name: "Incheon International Airport, Seoul, South Korea" },
  { id: "NRT", name: "Narita International Airport, Tokyo, Japan" },
  { id: "SIN", name: "Singapore Changi Airport, Singapore" },
  { id: "BKK", name: "Suvarnabhumi Airport, Bangkok, Thailand" },

  // South America
  {
    id: "GRU",
    name: "São Paulo/Guarulhos–Governador André Franco Montoro International Airport, São Paulo, Brazil",
  },
  {
    id: "EZE",
    name: "Ministro Pistarini International Airport, Buenos Aires, Argentina",
  },

  // Australia
  { id: "SYD", name: "Sydney Kingsford Smith Airport, Sydney, Australia" },
  { id: "MEL", name: "Melbourne Airport, Melbourne, Australia" },

  // Africa (excluding Nigeria)
  {
    id: "CPT",
    name: "Cape Town International Airport, Cape Town, South Africa",
  },
  {
    id: "JNB",
    name: "O.R. Tambo International Airport, Johannesburg, South Africa",
  },
  { id: "NBO", name: "Jomo Kenyatta International Airport, Nairobi, Kenya" },
  { id: "ACC", name: "Kotoka International Airport, Accra, Ghana" },

  // Middle East
  { id: "TLV", name: "Ben Gurion International Airport, Tel Aviv, Israel" },
  { id: "DOH", name: "Hamad International Airport, Doha, Qatar" },

  // Central America and Caribbean
  { id: "PTY", name: "Tocumen International Airport, Panama City, Panama" },
  {
    id: "SJU",
    name: "Luis Muñoz Marín International Airport, San Juan, Puerto Rico",
  },
];

export const airports = [
  {
    value: "LOS",
    label: "Murtala Muhammed International Airport, Lagos (LOS)",
  },
  {
    value: "ABV",
    label: "Nnamdi Azikiwe International Airport, Abuja (ABV)",
  },
  {
    value: "PHC",
    label: "Port Harcourt International Airport, Port Harcourt (PHC)",
  },
  {
    value: "KAN",
    label: "Mallam Aminu Kano International Airport, Kano (KAN)",
  },
  { value: "ENU", label: "Akanu Ibiam International Airport, Enugu (ENU)" },
  {
    value: "CBQ",
    label: "Margaret Ekpo International Airport, Calabar (CBQ)",
  },
  {
    value: "SOK",
    label: "Sadiq Abubakar III International Airport, Sokoto (SOK)",
  },
  { value: "AKR", label: "Akure Airport, Akure (AKR)" },
  { value: "BNI", label: "Benin Airport, Benin City (BNI)" },
  { value: "IBA", label: "Ibadan Airport, Ibadan (IBA)" },
  {
    value: "JFK",
    label: "John F. Kennedy International Airport, New York (JFK)",
  },
  { value: "LHR", label: "Heathrow Airport, London (LHR)" },
  { value: "HND", label: "Tokyo Haneda Airport, Tokyo (HND)" },
  { value: "DXB", label: "Dubai International Airport, Dubai (DXB)" },
  { value: "CDG", label: "Charles de Gaulle Airport, Paris (CDG)" },
  { value: "SIN", label: "Singapore Changi Airport, Singapore (SIN)" },
  { value: "SYD", label: "Sydney Kingsford Smith Airport, Sydney (SYD)" },
  { value: "HKG", label: "Hong Kong International Airport, Hong Kong (HKG)" },
  {
    value: "LAX",
    label: "Los Angeles International Airport, Los Angeles (LAX)",
  },
  { value: "FRA", label: "Frankfurt Airport, Frankfurt (FRA)" },
];
